### ISSUE TITLE
BUG: lost_reset is stubbornly failing on my aarch64 test system (again)

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-testsuite#100]
The `lost_reset` test continues to be the most fragile test in this test suite.  What was once happening occasionally appears to happening with more frequency.  Example test failure:
```
Running as   user    root
        with context unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
        on   system  Fedora

backlog_wait_time_actual_reset/test .. ok
exec_execve/test ..................... ok
exec_name/test ....................... ok
file_create/test ..................... ok
file_delete/test ..................... ok
file_rename/test ..................... ok
filter_exclude/test .................. ok
filter_saddr_fam/test ................ ok
filter_sessionid/test ................ ok
login_tty/test ....................... ok
# Test 4 got: "0" (lost_reset/test at line 166)
#   Expected: "1"
#  lost_reset/test line 166 is: ok( $found_msg, 1 );              # Was the message well-formed?
# Failed test 5 in lost_reset/test at line 167
#  lost_reset/test line 167 is: ok( $reset_rc == $reset_msg );    # Do the two lost values agree?
lost_reset/test ...................... 
Failed 2/5 subtests 
netfilter_pkt/test ................... ok
syscalls_file/test ................... ok
syscall_module/test .................. ok
time_change/test ..................... ok
user_msg/test ........................ ok
fanotify/test ........................ ok
bpf/test ............................. ok

Test Summary Report
-------------------
lost_reset/test                    (Wstat: 0 Tests: 5 Failed: 2)
  Failed tests:  4-5
Files=18, Tests=202, 53 wallclock secs ( 0.17 usr  0.04 sys +  8.67 cusr  3.32 csys = 12.20 CPU)
Result: FAIL
Failed 1/18 test programs. 2/202 subtests failed.
```

**Comment by rgbriggs** [comment]
On 2021-02-02 08:01, Paul Moore wrote:
> The `lost_reset` test continues to be the most fragile test in this test suite.  What was once happening occasionally appears to happening with more frequency.  Example test failure:

I found issues with this test in testing backports.  Incrementing the
sleep 1 at line 115 to sleep 3 fixed it along with another "service
auditd start" immediately after.  This value seems arbitrary and
has the potential to fail in the future.  A second syncmarker at that
point might be a better solution.

> ```
> Running as   user    root
>         with context unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
>         on   system  Fedora
> 
> backlog_wait_time_actual_reset/test .. ok
> exec_execve/test ..................... ok
> exec_name/test ....................... ok
> file_create/test ..................... ok
> file_delete/test ..................... ok
> file_rename/test ..................... ok
> filter_exclude/test .................. ok
> filter_saddr_fam/test ................ ok
> filter_sessionid/test ................ ok
> login_tty/test ....................... ok
> # Test 4 got: "0" (lost_reset/test at line 166)
> #   Expected: "1"
> #  lost_reset/test line 166 is: ok( $found_msg, 1 );              # Was the message well-formed?
> # Failed test 5 in lost_reset/test at line 167
> #  lost_reset/test line 167 is: ok( $reset_rc == $reset_msg );    # Do the two lost values agree?
> lost_reset/test ...................... 
> Failed 2/5 subtests 
> netfilter_pkt/test ................... ok
> syscalls_file/test ................... ok
> syscall_module/test .................. ok
> time_change/test ..................... ok
> user_msg/test ........................ ok
> fanotify/test ........................ ok
> bpf/test ............................. ok
> 
> Test Summary Report
> -------------------
> lost_reset/test                    (Wstat: 0 Tests: 5 Failed: 2)
>   Failed tests:  4-5
> Files=18, Tests=202, 53 wallclock secs ( 0.17 usr  0.04 sys +  8.67 cusr  3.32 csys = 12.20 CPU)
> Result: FAIL
> Failed 1/18 test programs. 2/202 subtests failed.
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/linux-audit/audit-testsuite/issues/100

- RGB

--
Richard Guy Briggs <rgb@redhat.com>
Sr. S/W Engineer, Kernel Security, Base Operating Systems
Remote, Ottawa, Red Hat Canada
IRC: rgb, SunRaycer
Voice: +1.647.777.2635, Internal: (81) 32635

**Comment by pcmoore** [comment]
> I found issues with this test in testing backports.  Incrementing the sleep 1 at line 115 to sleep 3 fixed it along with another "service auditd start" immediately after.  This value seems arbitrary and has the potential to fail in the future.  A second syncmarker at that point might be a better solution.

It's not clear to me, when you say you found issues with the `lost_reset` test, is that after the change in PR #101 or before?  If before, have you tried with the patch from PR #101?

**Comment by rgbriggs** [comment]
On 2021-02-02 13:30, Paul Moore wrote:
> It's not clear to me, when you say you found issues with the `lost_reset` test, is that after the change in PR #101 or before?  If before, have you tried with the patch from PR #101?

This was a year and a half ago.  Pausing auditd seems like a more graceful way of temporarily stopping the audit daemon.  But if I understand correctly, it doesn't change auditd's registration status in the kernel.

**Comment by pcmoore** [comment]
The difference between stopping and pausing auditd is that when we stop auditd it gracefully exits, informing the kernel that there is no longer an auditd collecting records *before* the backlog fills.  If we simply pause auditd then the kernel has no idea that auditd is no longer actively pulling records off the various backlog queues, it forces the kernel to do more work to figure that out.

Look at `kauditd_thread()`, if there is no auditd registered we fail pretty quickly and move the records off to the hold queue.  However, if there is an auditd registered we try really hard to flush the hold and retry queues before we ultimately give up on auditd and kick the connection.

**Comment by pcmoore** [comment]
Anyway, to get back to the original point - it sounds like you are okay with the PR that was merged today so I'll leave this closed.  If you are still seeing problems that are fairly frequent let me know.

**Comment by rgbriggs** [comment]
On 2021-02-02 15:29, Paul Moore wrote:
> The difference between stopping and pausing auditd is that when we stop auditd it gracefully exits, informing the kernel that there is no longer an auditd collecting records *before* the backlog fills.  If we simply pause auditd then the kernel has no idea that auditd is no longer actively pulling records off the various backlog queues, it forces the kernel to do more work to figure that out.
> 
> Look at `kauditd_thread()`, if there is no auditd registered we fail pretty quickly and move the records off to the hold queue.  However, if there is an auditd registered we try really hard to flush the hold and retry queues before we ultimately give up on auditd and kick the connection.

Especially with a queue of 1.

**Comment by rgbriggs** [comment]
On 2021-02-02 15:30, Paul Moore wrote:
> Anyway, to get back to the original point - it sounds like you are okay with the PR that was merged today so I'll leave this closed.  If you are still seeing problems that are fairly frequent let me know.

Yes.
