### ISSUE TITLE
RFE: improved documentation for installing and running the testsuite

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-testsuite#20]
Right now the README isn't very complete when it comes documentation about installing and running the tests.  At the very least we should have instructions for the different supported RHEL versions and upstream/Rawhide; ideally we would have instructions for non Red Hat distributions too, e.g. Debian/Ubuntu.

**Comment by The-Mule** [comment]
Based on a discussion in #40 - documentation should clearly state that each test must be "standalone" (audit-testsuite <=> a collection of self-contained "reproducers" that could be useful outside of the testsuite). #38 should be updated to cover this.

**Comment by pcmoore** [comment]
Let's leave #38 as-is, we can resolve the issue you describe in a separate PR/patch.

**Comment by pcmoore** [comment]
We have improved the documentation in a number of areas, and this issue is a bit ambiguous anyway so let's close it out.
