### ISSUE TITLE
Q: what to do with stress tests and potentially destructive tests?

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-testsuite#29]
We don't want to include stress tests and/or potentially destructive tests in the standard audit-testsuite, but this doesn't mean we don't want to track these tests for occasional, manual testing.  This issue has been created to discuss how best to handle these tests.

**Comment by pcmoore** [comment]
One possibility is to simple store the tests in a subdirectory in the current audit-testsuite that isn't normally built/executed.

**Comment by pcmoore** [comment]
One example test/reproducer taken from https://github.com/linux-audit/audit-kernel/issues/30:

* https://gist.githubusercontent.com/dvyukov/c19cadd309791cf5cb9b2bf936d3f48d/raw/1743ba0211079a5465d039512b427bc6b59b1a76/gistfile1.txt

**Comment by rgbriggs** [comment]
This would seem like the right place to park such tests, but to have an easy way to invoke the test with a Makefile target.

**Comment by rgbriggs** [comment]
It would appear this issue has been resolved since the tests_manual directory was created wtih a test already admitted.  Can we close this issue as resolved?

**Comment by pcmoore** [comment]
Sounds good to me.
