### ISSUE TITLE
RFE: Add test for presence of 32-bit socketcall args on 64-bit systems

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-testsuite#32]
Test for the presence of 32-bit socketcall arguments on 64-bit systems as appears to be missing in https://github.com/linux-audit/audit-kernel/issues/14

Note: This would be more useful if it tested the presence of correctly formed socketcall args in all systems.

**Comment by pcmoore** [comment]
It is worth noting that socketcall(2) is not valid on a number of arch/ABIs, e.g. aarch64.  I know that 32-bit x86, 32-bit MIPS, PA-RISC, 32/64-bit Power, and 31/64-bit s390 support socketcall(2) but I am not sure of any others.

For the first iteration of the test I think it is reasonable to target just 32-bit x86 (so long as the test is written such that the test still executes on x86_64 in 32-bit mode) and it can later be expanded to other arch/ABIs as time permits.

**Comment by rgbriggs** [comment]
It turns out I don't even need a server listening to test this.

**Comment by rgbriggs** [comment]
Updated test pushed to my fork:
https://github.com/linux-audit/audit-testsuite/pull/34/commits/282cecc9824104575e49d98458c07b7ef18b11af

**Comment by pcmoore** [comment]
Quick link to @rgbriggs's PR: https://github.com/linux-audit/audit-testsuite/pull/34 (from where the link above points)

**Comment by pcmoore** [comment]
Fixed in e276b30a63c335f73155cdaac614b700d5f17cea.

**Comment by pcmoore** [comment]
@rgbriggs I'm reopening this issue because the syscall_socketcall test spews an error message that is misleading (see below); tests should not output extraneous output like this.

A quick glance would indicate this is due to some error messages being displayed in the _conn.c_ test helper.  Fix this please.

    Running as   user    root
            with context unconfined_u:unconfined_r:unconfined_t
            on   system  Fedora
    
    exec_execve/test ......... ok
    exec_name/test ........... ok
    file_create/test ......... ok
    file_delete/test ......... ok
    file_rename/test ......... ok
    filter_exclude/test ...... ok
    filter_sessionid/test .... ok
    login_tty/test ........... ok
    syscalls_file/test ....... ok
    syscall_socketcall/test .. ERROR connecting: Connection refused
    syscall_socketcall/test .. ok
    user_msg/test ............ ok
    All tests successful.
    Files=11, Tests=54,  3 wallclock secs ( 0.04 usr  0.03 sys +  0.68 cusr  0.69 csys =  1.44 CPU)

**Comment by rgbriggs** [comment]
Fixup update on https://github.com/rgbriggs/audit-testsuite/tree/ghak14-32bit-binary-misses-AUDIT_SOCKETCALL-x86_64

**Comment by pcmoore** [comment]
Fix merged via e5b11b648188e0ddb227c8cc42846251670ee71e.
