### ISSUE TITLE
RFE: Testing module for common subroutines

### ISSUE THREAD

**Issue by The-Mule** [linux-audit/audit-testsuite#40]
There are several patterns used in tests which can be moved to our testing module to avoid duplication and speed up the process of writing new tests. Each test works more or less as follows:

1. Setup: add new audit rules and temporary files.
2. Trigger: generate audit events.
3. Verification: verify that correct events were generated.
4. Clean-up: restore audit rules and remove temporary files.

At the moment, I see the following candidates of "common subroutines" for this testing module:

1. Setup: unique key generation, audit rules backup, auditd conf backup, create temporary files
2. Trigger: none, this is usually very specific to tested functionality 
3. Verification: traversing audit event to check it meets specification
4. Clean-up: restore rules and configuration, remove temporary files

As I mentioned somewhere else, clean-up should be handled as a list of callbacks so that it can be called by a signal handler (to make sure it always happens). 

What do you think? I will prepare some example in a separate branch to have some code to discuss.

**Comment by rgbriggs** [comment]
This all sounds reasonable.

Setup will certainly benefit for most tests, but some tests don't need a key, or need a custom indentifier, or need additional temporary files.  So, a default setup call with ability to add custom setup should work.  The specific rules needed for a particular test would go into this unless they need to be interleaved with the trigger procedure.

The Clean-up section as you point out would be helped the most by this refactoring for common subroutines, particularly in case of abnormal termination (except crash).

**Comment by rgbriggs** [comment]
Another one that comes to mind is the -ts $starttime code that I wrote up to only look at messages since a specific time in the ghak8 test case branch https://github.com/rgbriggs/audit-testsuite/compare/ghak8-module-path-spam.passive

**Comment by pcmoore** [comment]
One of my goals of the testsuite was to create a collection of self-contained "reproducers" that could be useful outside of the testsuite; creating a separate, common testing module violates this goal.  I'll leave this issue open for some more discussion, but right now I'm leaning towards closing this as WONTFIX.

**Comment by The-Mule** [comment]
That is a very good point Paul. Let's stick to that for now but let's make this goal clearly visible in README then (I must admit I was not aware of this goal). So this issue basically collides with #30. Nevertheless, I like the idea of having a set of self-contained reproducers and we are still very close to that (according to #30). Clearly there will be a lot of duplicated code across the tests but I do not see it as a problem as long as it advocated by a good reason. We can start by adding a new section "Writing a Test" into README to cast this goal in stone :).

**Comment by The-Mule** [comment]
I am closing this issue for now based on previous two comments.
