### ISSUE TITLE
RFE: check for audit_filter_rules() cred memory leak

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-testsuite#47]
Commit c69e8d9c01db ("CRED: Use RCU to access another task's creds and to
release a task's own creds") introduced a cred struct memory leak when the second of the three return conditions in the audit_filter_rules() didn't call put_cred() to match the initial get_task_cred().  This second exit condition tests if a subsequent rule has a higher priority and if it does not it simply exits, but should first call put_cred().

Test for this condition by looking for a matching number of cred_jar entries in the slab.

**Comment by rgbriggs** [comment]
This bug was fixed upstream by f562988350361bf4118dd3c3e192dff763b493d9 .

**Comment by pcmoore** [comment]
This sounds like an issue to create a test for a specific bug dealing with an internal kernel memory leak; this isn't really the target for the audit-testsuite so I'm going to close this.  If I've characterized this issue incorrectly please comment and/or reopen.
