### ISSUE TITLE
Q: filter_execlude fail with "Only msgtype field can be used with exclude filter"

### ISSUE THREAD

**Issue by gaochong2016** [linux-audit/audit-testsuite#52]
So like "auditctl -d exclude,always -F pid=$pid" will fail.
I have use repo http://mirror.centos.org/centos/7/updates/x86_64/Packages/  yum update to audit-2.6.5.

Am I need update kernel from rhel7.2 to rhel7.3 ?

Thank you~

**Comment by rgbriggs** [comment]
This doesn't seem like a test suite bug.  This question should be asked on the linux-audit@redhat.com mailing list.

The exclude filter was extended in:
 upstream kernel v4.9
 audit-2.7

It is not in a released RHEL yet.
