### ISSUE TITLE
RFE: create a debug flag/option so we have a consistent way to toggle debugging output

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-testsuite#54]
Create a mechanism to toggle a global test debug flag which tests can use to decide if any additional output should be displayed.  I imagine an environment variable is probably the easiest approach, but I'm open to suggestions.

**Comment by pcmoore** [comment]
@rgbriggs As you have complained the loudest about this, I would like to hear any ideas you might have on this.

**Comment by rgbriggs** [comment]
I don't have a strong opinion about this and would defer to you or Ondrej who appear to be more comfortable in PERL and the framework of this test suite.  A method that allows a number of different ways of invoking the tests would be helpful including Ondrej's way to run single tests and the more obvious method of changing to the test script directory and running it directly (./test), as well as running the entire suite from the top level makefile.  It could also be pulled from a common functions file, or it could be a config variables file that is pulled in.

See: https://github.com/linux-audit/audit-testsuite/issues/40 (Testing module for common subroutines)
See: https://github.com/linux-audit/audit-testsuite/issues/30 (tests should not depend on environment variables )

**Comment by pcmoore** [comment]
> See: #30 (tests should not depend on environment variables )

To be clear, there is a difference in using the presence/value of an environment variable to trigger a debug state and causing the normal operation of a test to fail if the environment variable is not defined/present. 
 The former is acceptable, the latter is not (this is what #30 is about).

**Comment by pcmoore** [comment]
Closed with commit 29aa5323c52d4b1b82b6b6ad8def44cbfe5a6ee0, if this doesn't prove sufficient we can revisit in the future.
