### ISSUE TITLE
BUG: sporadic failures in lost_reset

### ISSUE THREAD

**Issue by pcmoore** [linux-audit/audit-testsuite#56]
Lately I've been seeing sporadic test failures in the lost_reset test.  I haven't had an opportunity to debug these failures to the level of determining the root cause, so I'm creating this issue to track the history/progress of the bug.

@The-Mule I believe you have been seeing these failures too in some automated test runs, any chance you have looked into this at all?

@rgbriggs This test has been pretty reliable for me up until recently, have you noticed any failures?

**Comment by pcmoore** [comment]
The exact failure seen while running the entire test suite:

    lost_reset/test .......... 13/15 # Failed test 15 in lost_reset/test at line 99
    #  lost_reset/test line 99 is: ok( $result_lost == $lost );    # Do the two lost values agree?
    lost_reset/test .......... Failed 1/15 subtests 

My test system:

    # uname -r
    4.14.0-0.rc6.git0.1.1.secnext.fc28.x86_64
    # rpm -q audit
    audit-2.8.1-1.fc28.x86_64

**Comment by rgbriggs** [comment]
On 2017-10-24 18:32, Paul Moore wrote:
> The exact failure seen while running the entire test suite:
> 
>     lost_reset/test .......... 13/15 # Failed test 15 in lost_reset/test at line 99
>     #  lost_reset/test line 99 is: ok( $result_lost == $lost );    # Do the two lost values agree?
>     lost_reset/test .......... Failed 1/15 subtests 
> 
> My test system:
> 
>     # uname -r
>     4.14.0-0.rc6.git0.1.1.secnext.fc28.x86_64
>     # rpm -q audit
>     audit-2.8.1-1.fc28.x86_64

Same kernel and userspace, not seeing a problem here.

**Comment by pcmoore** [comment]
@rgbriggs well, it's sporadic.  Did you run it once, or multiple times?  If the latter, how many times?

Do you regularly run the test against the latest audit userspace from Rawhide and the pcmoore/kernel-secnext COPR kernels?  In my experience running the test in that environment multiple times a week, I may see it only happen once.

**Comment by rgbriggs** [comment]
On 2017-11-01 16:14, Paul Moore wrote:
> @rgbriggs well, it's sporadic.  Did you run it once, or multiple
> times?  If the latter, how many times?

I ran it a small handful of times.  On re-running it many times I was
able to reproduce the issue.  I've just pushed an update that should
make those failures a lot more rare.  In the process also made repeated
tests run more reliably without having to wait 10 minutes to ensure the
"recent" timer expires.  I also potentially found a bug in userspace
"auditctl --lost-reset" when the lost value is "0", it returns "2".

https://github.com/linux-audit/audit-testsuite/compare/master...rgbriggs:ghat56-audit-lost-reset

I'm getting concerned that all the queue efficiencies that you and Steve
have done in kernel and userspace are making it more and more difficult
to trigger lost messages.  :-)

> Do you regularly run the test against the latest audit userspace from
> Rawhide and the pcmoore/kernel-secnext COPR kernels?  In my experience
> running the test in that environment multiple times a week, I may see
> it only happen once.

I only recently got the secnext kernels running.  I occasionally run the
rawhide userspace.  I usually run from local devel trees for userspace
and kernel.

**Comment by pcmoore** [comment]
> I ran it a small handful of times.  On re-running it many times I was
able to reproduce the issue.  I've just pushed an update that should
make those failures a lot more rare.

My only worry is that are we simply chasing iterators/timers and we are doomed to keep tweaking the values as we try to outrun the kernel.  It would be really nice if we could find a way to test this without racing the kernel, but I'm not sure that exists.

> I'm getting concerned that all the queue efficiencies that you and Steve
have done in kernel and userspace are making it more and more difficult
to trigger lost messages.  :-)

To quote the Simpsons, "Remove The Stone Of Shame... Attach The Stone Of Triumph!"

**Comment by rgbriggs** [comment]
There have been two mitigations submitted to address this issue: one to tune the test parameters to more aggressively trigger it, and the second was a bug found in userspace code that triggered it.  A patch to fix the latter has been accepted to upstream userspace so this issue is very unlikely to be triggered again.  Could the former be accepted as in incremental improvement and close this issue unless a better method is identified, or re-open the issue if it is triggered again or a better method is found later?

**Comment by rgbriggs** [comment]
Due to the test reset bug (backlog_limit and backlog_wait_time) observation suggests that a potential method to increment lost count is to set these two parameters to their minimum values (1) and provoke a log rotation (which is usually provoked by cron?).

**Comment by pcmoore** [comment]
> There have been two mitigations submitted to address this issue: one to tune the test parameters to more aggressively trigger it ...

For reference, this is the PR I believe @rgbriggs was talking about: #60.

**Comment by The-Mule** [comment]
I tested the latest version on both RHEL7 and Fedora-Rawhide and the test seems to be working fine now. There are a few other issues already tracked in #62. I thinks that is the only remaining issue, once fixed, we can close this one, hopefully.

**Comment by pcmoore** [comment]
I haven't seen this in some time, and commit 49eb1760e2b8a4f5d0747ef59f493976ab9ba72f should hopefully resolve any lingering problems, so let's close this issue for now.
