### ISSUE TITLE
RFE: add test for fanotify events

### ISSUE THREAD

**Issue by The-Mule** [linux-audit/audit-testsuite#63]
Based on its settings fanotify subsystem can produce type=FANOTIFY events. We need a test that audit records are created only when it is needed and that they are associated with other records (PROCTITLE, SYSCALL, CWD, PATH).

**Comment by pcmoore** [comment]
@The-Mule it sounds like you were planning on working on this, should I assign this task to you?

**Comment by The-Mule** [comment]
@pcmoore yes, please.

**Comment by pcmoore** [comment]
All set, thanks.

**Comment by The-Mule** [comment]
PR #66

**Comment by The-Mule** [comment]
Merged PR#66 resolved this issue.
