### ISSUE TITLE
BUG: fix references to b64 on generic tests

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-testsuite#78]
Several tests have embedded references to 64-bit architecture rules when they may be run on 32-bit architecture machines.  Convert them from "-F arch=b64" to "-F arch=b$ENV{MODE}".

tests/filter_sessionid/test:
  "auditctl -a always,exit -F arch=b64 -F path=/tmp/$key -F sessionid=$sessionid -k $key"
tests/syscall_module/test:
  "auditctl -a always,exit -F arch=b64 -S init_module -S finit_module -k $key-load"
tests/syscall_module/test:
  system("auditctl -a always,exit -F arch=b64 -S delete_module -k $key-unload");
tests_manual/syscall_module_path_filter/setup:
  echo "-a always,exit -F arch=b64 -S init_module -S finit_module -k ghak8-mod-load" ...

**Comment by pcmoore** [comment]
@rgbriggs I'm going to assign this to you for no other reason than you created the issue, if you would prefer to leave it open/unassigned let me know.

**Comment by rgbriggs** [comment]
Merged: 6d65bf163eb8 ("tests: update rules to select correct arch")
