### ISSUE TITLE
BUG: lost_reset fails to lose messages on some systems, failing test

### ISSUE THREAD

**Issue by rgbriggs** [linux-audit/audit-testsuite#79]
Some recent systems appear to be so robust that provoking lost messages is proving difficult if not impossible.  The offending commit appears to be:
5a6f30a435dc7f3958aba344203c68fd112c5e06 ("lost_reset: spin until msg lost")

@pmoore's method of deleting the "-F pid=$ping_pid" argument to the "auditctl -a ..." line of tests/lost_reset/test succeeds on these stubborn systems to trigger lost messages, but is pretty saddistic on any kernel, worse on older ones.

**Comment by WOnder93** [comment]
How about we first try to trigger the message with `-F pid=$ping_pid` and if that fails, we retry using the more aggressive variant without `-F pid=$ping_pid`? That way we avoid the sadistic testing on most systems, but still ensure the test works even on the stubborn machines.

**Comment by rgbriggs** [comment]
On 2019-01-10 01:43, Ondrej Mosnáček wrote:
> How about we first try to trigger the message with `-F pid=$ping_pid` and if that fails, we retry using the more aggressive variant without `-F pid=$ping_pid`? That way we avoid the sadistic testing on most systems, but still ensure the test works even on the stubborn machines.

Yes, that sounds like a reasonable approach.

**Comment by pcmoore** [comment]
Fixed via cd9c6ea8b366fa8d090a2de5b5e6c5aa3445f714.
