### ISSUE TITLE
Q: why does tests/Makefile override PATH?

### ISSUE THREAD

**Issue by WOnder93** [linux-audit/audit-testsuite#84]
https://github.com/linux-audit/audit-testsuite/blob/38f7a5f97ccb1be778c11e2b358d4f8222a9c651/tests/Makefile#L55

^^^ I just spent the last hour figuring out why the testsuite doesn't work with locally installed audit userspace binaries until I found this line... Does it serve any particular purpose? Can we please remove it and let the user of the testsuite set the PATH variable as it suits them?

**Comment by pcmoore** [comment]
This looks like a carryover from the selinux-testsuite, not something what was explicitly added to solve a specific problem with the audit-testsuite.

I don't have a problem with removing the explicit PATH redefinition, patches are always welcome :)

**Comment by WOnder93** [comment]
OK, great, I'll send a patch then :)
